steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'extract-financial-data',
           '--entry-point', 'extract',
           '--runtime', 'python310',
           '--trigger-http',
           '--allow-unauthenticated',
           '--region', 'us-east1',
           '--service-account', 'cloud-functions-deployer@ba882-jsale.iam.gserviceaccount.com',
           '--source', '/home/jsale017/Predictive-Financial-Analytics-Financial-APIs/functions/extract-rss/',
           '--no-gen2']
